Jefersonsteven/tools-match

pages/api/registerUser/index.js
Ruta para concetar el front con el backend mediante la peticion a esta ruta que permite crear un usuario nuevo cuando se completa el formulario de registro
=> Ruta para el formulario de registro y crear usurio

pages/api/forgetPassword/index.js
Ruta para enlazar el front con el back para actualizar la contraseña desde el formulario 'Olvide mi contraseña' en caso de que el usuario se haya olvidado de ella
=> Ruta para actualizar la contraseña en form 'Olvide mi contraseña'

pages/api/logoutUser/[email].js
Ruta que utlizará el fornt para cerrar la sesión del usuario
=> Ruta para cerrar la sesión del usuario

src/app/landing/Landing.jsx, src/app/page.js, src/components/Header/Header.jsx, src/components/team/Team.jsx, src/components/team/Team.module.css
Create new Team branch for Team Components.
=> creating new branch Team

src/components/shoppingCart/ShoppingCart.jsx
**Jefferson** This is the correct pull request because the previous pull request went to the main branch.
Creating the shoppingCart branch in Components.
=> creating shoppingCart branch

pages/api/loginValidate/index.js, pages/api/logoutUser/[email].js
Rutas optimizadas para cuando ingresa sesión el usuario o sale de ella
=> Rutas login and logout

next.config.js, package-lock.json, package.json, src/app/uploadimage/page.jsx, src/components/Cloudinary/cloudinary.js, src/components/Cloudinary/upload.js, src/components/Cloudinary/useUpload.js
Added an example application in app's uploadimage folder you can delete later
=> Cloudinary images with a custom hook

src/app/cart/Cart.module.css, src/app/cart/page.jsx
Button to remove the cards from the shopping cart and subtract from the total price, when customers go to another page the product will continue to be available in the cart, and when the customer clicks on the buy button, the products disappear from the cart, buttons are also added to the card Add to cart.
=> feature/shoppingcart/adriana s/develop

pages/api/admin/review/[id].js, pages/api/admin/review/index.js, pages/api/admin/user/[id].js, pages/api/admin/user/index.js, pages/api/post/[id].js, pages/api/review/[id].js, pages/api/review/index.js, pages/api/user/[id].js, prisma/migrations/20230516202653_received_reviews/migration.sql, prisma/schema.prisma
la data que trae cambio en cuanto a reviews en el usuario para guardar las que hayan hecho en sus publicaciones, reviews debe dar id de a quien va la review (id del usuario)
=> received reviews

pages/api/admin/paginatedUser/index.js
se crea la ruta para el paginado de usuarios
=> creando ruta back

package-lock.json, pages/api/admin/user/[id].js, pages/api/maps/mapUtil.js
auto getmap by getting user on /admin/user/id
=> autogetmap on get admin/user/id

pages/api/admin/hidden/post/index.js, pages/api/admin/hidden/review/index.js, pages/api/admin/hidden/user/index.js
/admin/hidden/user  &  post   &  review
=> hidden eps

pages/api/admin/hidden/post/index.js, pages/api/admin/hidden/review/index.js, pages/api/admin/hidden/user/index.js, pages/api/admin/post/index.js, pages/api/admin/review/index.js, pages/api/admin/user/index.js
new eps to bulkdelete or bulgrevive xd all available data (hidden value)
=> new eps to recovery all data

src/components/Filter/FilterBar.jsx, src/components/Filter/UseFetchCard.js
filtrado del front end conectado con el back
=> filtros del front conectados con el back

src/app/cart/page.jsx
=> remove items from cart

pages/api/admin/hidden/user/index.js, pages/api/admin/user/[id].js, pages/api/admin/user/index.js, pages/api/maps/index.js, pages/api/maps/mapUtil.js, pages/api/user/[id].js, src/app/pruebamapa/getLocation.js, src/app/pruebamapa/page.jsx
app/pruebamapa getLocation (funcion ejecutable en componente page para pedir permisos de localizacion)
backend:  post /api/maps por body:{latitude, longitude}
=> get map by location

src/app/landing/Landing.jsx, src/app/layout.js, src/app/perfil/[perfilId]/page.jsx, src/app/post/[postId]/page.jsx, src/components/Cards/Card.jsx, src/components/Header/Header.jsx
Limpiando errores en Landing, Perfil, Post, Card y Header.
=> Limpiando errores en Landing, Perfil, Post, Card y Header.

src/components/Reviews/CardsOrders.jsx, src/components/Reviews/FormReview.jsx, src/components/SearchBar/SearchBar.jsx
=> Feature/filter styles/celes

src/components/Filter/FilterBar.jsx, src/components/Filter/handlers.js, src/context/AppContext.jsx
se agrega la lógica del botón de limpiar filtros, se exportan los handlers de los botones, se deja un botón temporal para realizar las pruebas falta corregir el estilado del botón
=> se agrego con éxito el boton de limpiar filtros

src/components/Filter/FilterBar.jsx
se elimina el comentario del componente filterBar
=> Refactor/front/filter/boton limpiar filtros/develop/jean palomino

pages/api/sendEmail/contraEntregaComprador/index.js, pages/api/sendEmail/contraEntregaVendedor/index.js
Endpoint para enviar correo al comprador y vendedor cuando se selecciona contra entrega
=> Refactor/back/endpoint send mail/fi

src/app/perfil/[perfilId]/page.jsx, src/components/Reviews/CardsOrders.jsx
Sorry el otro se mergio a main
Es para que se renderizen las cards order
=> cardsOrdersOk FaltaEstilo

src/app/perfil/[perfilId]/page.jsx
=> Cambios en el perfil

src/app/form/assets/formSubmit.js, src/app/form/form.module.css, src/app/form/recover/page.jsx, src/app/form/resetPassword/[email]/page.jsx, src/app/perfil/[perfilId]/changePassword/page.jsx, src/app/perfil/[perfilId]/edit/page.jsx
Se mejoraron los estilos para presentar mañana
=> css modified

src/app/perfil/[perfilId]/edit/perfilForm.module.css, src/components/Filter/FilterBar.jsx, src/components/Filter/UseFetchCard.js, src/components/Filter/handlers.js, src/components/FilterRangeDistance/FilterRangeDistance.jsx, src/components/Header/Header.jsx, src/components/Reviews/CardsReview.jsx
=> Feature/distance post/jeffer

pages/api/sendEmail/baneo/index.js, pages/api/sendEmail/deleteReviews/index.js
Endpoint para enviar mail cuando se elimina una reseña de un usuario debido al incumplimiento de normas
=> Endpoint par aenviar mail cuando se elimina una reseña de un usuario

src/components/Reviews/CardsOrders.module.css, src/components/Reviews/CardsPurchasedItems.jsx, src/components/Reviews/CardsPurchasedItems.module.css
Estilado Purchased Items cards (modal)
=> estilos de las purchased cards ok

prisma/schema.prisma, src/app/crear-publicacion/page.jsx, src/app/payment/page.jsx, src/app/payment/payment.module.css, src/components/FilterRangeDistance/FilterRangeDistance.jsx
Cambia el botón de opciones de pago por un titulo.
fix: arregle el problema de que no se guardaban las coordenadas
=> Cambia el boton de opciones pagos por un titulo

src/app/payment/assets/alertConfirmPurchase.js, src/app/payment/page.jsx, src/app/post/[postId]/page.jsx, src/components/FilterRangeDistance/FilterRangeDistance.jsx, src/components/Header/Header.jsx, src/components/Header/Header.module.css
Se agrego el funcionamiento al botón de pago contra entrega y cambios del header e nav
=> Agregue la funcion de pago contra entrega

src/components/Reviews/FormUpdateReview.jsx
=> ya se puede editar la reseña

src/app/perfil/[perfilId]/page.jsx, src/components/Reviews/CardsCreatedReviews.jsx, src/components/Reviews/FormUpdateReview.jsx
Arregle un bug para editar resenia. Gracias.
=> Feature/cards purchased items/celes

src/components/Filter/FilterBar.jsx, src/components/Filter/FilterBar.module.css
Boton Filtro Pais 
Filter alignments
=> filtros styles

src/app/home/Home.module.css, src/app/home/Slider.jsx, src/app/home/page.jsx, src/components/Cards/Cards.jsx, src/components/Filter/FilterBar.jsx
=> Feature/country button filter/celes

src/components/Reviews/CardsOrders.jsx, src/components/Reviews/CardsPurchasedItems.jsx, src/components/Reviews/CardsPurchasedItems.module.css
Estilado a la vista previa de crear reseña donde aparecen los productos de la orden de compra seleccionada
=> Estilado a la vista previa al crear reseña

src/app/payment/page.jsx, src/app/payment/payment.module.css
Responsive el formulario de compras, 😎
=> Responsive Formulario de compras

src/app/post/[postId]/page.jsx, src/app/post/[postId]/post.module.css
Agregue los dias de arriendo al detail
=> Agregue los dias de arriendo al detail

src/app/perfil/[perfilId]/page.jsx, src/components/Reviews/CardsCreatedReviews.jsx, src/components/Reviews/CardsOrders.jsx, src/components/Reviews/CardsPurchasedItems.jsx, src/components/Reviews/CardsPurchasedItems.module.css, src/components/Reviews/FormReview.jsx
Delete working
Rerenderizacion de reviews editadas 
Re renderizacion de productos que se les dejo review
Alerta confirmacion eliminacion de resenia
resenia recibida/crada filtro hidden false
=> Feature/renderizado reviews/celes

src/components/Reviews/CardsOrders.jsx, src/components/Reviews/CardsOrders.module.css, src/components/Reviews/CardsPurchasedItems.jsx, src/components/Reviews/CardsPurchasedItems.module.css, src/components/Reviews/FormReview.jsx, src/components/Reviews/FormReview.module.css
Estilado de la vista cuando se selecciona una order
=> Refactor/front/responsive create review/fi

pages/api/sendEmail/baneo/index.js, pages/api/sendEmail/confirm/index.js, pages/api/sendEmail/contraEntregaComprador/index.js, pages/api/sendEmail/contraEntregaVendedor/index.js, pages/api/sendEmail/deletePost/index.js, pages/api/sendEmail/deleteReviews/index.js, pages/api/sendEmail/desbaneo/index.js, pages/api/sendEmail/envio/index.js, pages/api/sendEmail/register/index.js, pages/api/sendEmail/registerGoogle/index.js, pages/api/sendEmail/resetPassword/index.js, pages/api/sendEmail/reviews/index.js, pages/api/sendEmail/sendReview/index.js, pages/api/sendEmail/terminosCondiciones/index.js
Mails para enviar a los usuarios dependiendo el caso
=> Mails para los usuarios

pages/api/admin/report/[email].js, pages/api/admin/report/index.js
se crea el endpoint report para actualizar los reportes   y para traer los reportes que tiene el usuario
=> endpoint creado con exito

pages/api/filters/allFilters/index.js, pages/api/orderings/orderAlphabetically/index.js, pages/api/orderings/orderPrice/index.js, pages/api/orderings/orderRating/index.js, src/components/Filter/FilterBar.jsx, src/components/Filter/handlers.js
se agrega el botón para filtrar  por todos los países
=> boton agregado con exito

src/components/Reviews/CardsOrders.jsx, src/components/Reviews/CardsPurchasedItems.jsx
Se agrego width y heihgt a la imagen de la order
=> add width in image

src/app/favorite/Favorites.module.css, src/app/favorite/page.jsx
=> fixing favorites

pages/api/admin/report/index.js, pages/api/orderings/orderRating/index.js, src/components/Cards/Cards.jsx, src/components/Filter/FilterBar.jsx, src/components/Filter/UseFetchCard.js, src/components/Filter/handlers.js, src/components/FilterRangeDistance/FilterRangeDistance.jsx, src/components/SearchBar/SearchBar.jsx, src/components/paginated/Paginated.jsx, src/context/AppContext.jsx
=> Refactor/front/button filter country/jean palomino/develop

pages/api/filters/allFilters/index.js, pages/api/orderings/orderAlphabetically/index.js, pages/api/orderings/orderPrice/index.js, src/components/Cards/assets/calculateAverage.js
se agrega la función para retornar el proemdio de las puntuaciones y me modifican las rutas  para que traigan las propiedad review
=> Refactor/front/cards/funcion rating/jean palomino/develop

pages/api/admin/postByCountry/[id].js, src/components/Cards/Card.jsx, src/components/Cards/Cards.jsx, src/components/Cards/assets/calculateAverage.js
se modificó  una ruta para traer las reviews
=> modifiaacndo filtros

src/app/dashboard/layout.js, src/app/dashboard/publications/page.jsx, src/app/dashboard/reviews/page.jsx, src/app/dashboard/users/page.jsx, src/app/dashboard/usersBan/page.jsx
Nombre en las alertas y que se actualize, ultimo cambio xd
=> nombreAlertas
